(function() {var implementors = {};
implementors["rustcv"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"rustcv/core/struct.Mat.html\" title=\"struct rustcv::core::Mat\">Mat</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"rustcv/dnn/struct.Net.html\" title=\"struct rustcv::dnn::Net\">Net</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"rustcv/features2d/struct.MSER.html\" title=\"struct rustcv::features2d::MSER\">MSER</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"rustcv/features2d/struct.SimpleBlobDetector.html\" title=\"struct rustcv::features2d::SimpleBlobDetector\">SimpleBlobDetector</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"rustcv/objdetect/struct.CascadeClassifier.html\" title=\"struct rustcv::objdetect::CascadeClassifier\">CascadeClassifier</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"rustcv/cuda/struct.GpuMat.html\" title=\"struct rustcv::cuda::GpuMat\">GpuMat</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"rustcv/cuda/struct.GpuCascade.html\" title=\"struct rustcv::cuda::GpuCascade\">GpuCascade</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
